// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZFine.Data;

namespace ZFine.Web.Migrations
{
    [DbContext(typeof(ZFineDbContext))]
    [Migration("20180925142230_Initial1")]
    partial class Initial1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ZFine.Data.DBContext.FilterIPEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Name");

                    b.Property<long>("Number");

                    b.Property<bool>("Sex");

                    b.HasKey("Id");

                    b.ToTable("FilterIP");
                });
#pragma warning restore 612, 618
        }
    }
}
